POST http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "Algum serviço 2",
    "description": "ALO ALO 2",
    "price": 2000,
    "image": "https://unsplash.com/pt-br/fotografias/um-caminho-de-terra-no-meio-de-um-deserto-rVdsDGh-TQ4"
}

###

GET http://localhost:3000/api/services
